USE [master]
GO
/****** Object:  Database [MidTermDB]    Script Date: 07/18/2025 11:38:58 ******/
CREATE DATABASE [MidTermDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MidTermDB', FILENAME = N'/var/opt/mssql/data/MidTermDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MidTermDB_log', FILENAME = N'/var/opt/mssql/data/MidTermDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MidTermDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MidTermDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MidTermDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MidTermDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MidTermDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MidTermDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MidTermDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MidTermDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MidTermDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MidTermDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MidTermDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MidTermDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MidTermDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MidTermDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MidTermDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MidTermDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MidTermDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MidTermDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MidTermDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MidTermDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MidTermDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MidTermDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [MidTermDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MidTermDB] SET RECOVERY FULL 
GO
ALTER DATABASE [MidTermDB] SET  MULTI_USER 
GO
ALTER DATABASE [MidTermDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MidTermDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MidTermDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MidTermDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MidTermDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MidTermDB', N'ON'
GO
ALTER DATABASE [MidTermDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [MidTermDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO
USE [MidTermDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET ACCELERATED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET CE_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DOP_FEEDBACK = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DW_COMPATIBILITY_LEVEL = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET EXEC_QUERY_STATS_FOR_SCALAR_FUNCTIONS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET FORCE_SHOWPLAN_RUNTIME_PARAMETER_COLLECTION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LAST_QUERY_PLAN_STATS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEDGER_DIGEST_STORAGE_ENDPOINT = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERCENTILE_GRANT = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERSISTENCE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SENSITIVE_PLAN_OPTIMIZATION = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PAUSED_RESUMABLE_INDEX_ABORT_DURATION_MINUTES = 1440;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO
USE [MidTermDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 07/18/2025 11:38:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Authors]    Script Date: 07/18/2025 11:38:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Authors](
	[AuthorId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Bio] [nvarchar](500) NULL,
 CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED 
(
	[AuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Books]    Script Date: 07/18/2025 11:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[BookId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](1000) NULL,
	[CoverImagePath] [nvarchar](255) NULL,
	[AuthorId] [int] NOT NULL,
 CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250718032713_Init', N'6.0.33')
SET IDENTITY_INSERT [dbo].[Authors] ON 

INSERT [dbo].[Authors] ([AuthorId], [Name], [Bio]) VALUES (2, N'George Orwell', N'English novelist, essayist, journalist.')
INSERT [dbo].[Authors] ([AuthorId], [Name], [Bio]) VALUES (3, N'J.K. Rowling', N'British author, best known for Harry Potter.')
INSERT [dbo].[Authors] ([AuthorId], [Name], [Bio]) VALUES (4, N'Kim Tùng', N'HEHEHE')
SET IDENTITY_INSERT [dbo].[Authors] OFF
SET IDENTITY_INSERT [dbo].[Books] ON 

INSERT [dbo].[Books] ([BookId], [Title], [Description], [CoverImagePath], [AuthorId]) VALUES (3, N'1984', N'A dystopian novel.', NULL, 2)
INSERT [dbo].[Books] ([BookId], [Title], [Description], [CoverImagePath], [AuthorId]) VALUES (4, N'Animal Farm', N'A political fable.', NULL, 2)
INSERT [dbo].[Books] ([BookId], [Title], [Description], [CoverImagePath], [AuthorId]) VALUES (5, N'Harry Potter and the Sorcerer''s Stone', N'First in the magical series.', NULL, 3)
INSERT [dbo].[Books] ([BookId], [Title], [Description], [CoverImagePath], [AuthorId]) VALUES (6, N'Nhà giả kim', N'Top 1 doanh thu', N'/images/covers/c5c5a57a-6364-4ebc-9c39-40d2dc4fb983.jpg', 4)
SET IDENTITY_INSERT [dbo].[Books] OFF
/****** Object:  Index [IX_Books_AuthorId]    Script Date: 07/18/2025 11:38:59 ******/
CREATE NONCLUSTERED INDEX [IX_Books_AuthorId] ON [dbo].[Books]
(
	[AuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Books]  WITH CHECK ADD  CONSTRAINT [FK_Books_Authors_AuthorId] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Authors] ([AuthorId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Books] CHECK CONSTRAINT [FK_Books_Authors_AuthorId]
GO
USE [master]
GO
ALTER DATABASE [MidTermDB] SET  READ_WRITE 
GO
